name: Trigger Jenkins Build on Main Branch Push

on:
  push:
    branches:
      - main

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: |
          # Replace <JENKINS_WEBHOOK_URL> with the actual URL of your Jenkins webhook
           curl -X POST -k http://18.235.237.182:8080/github-webhook/
